networkmgmt/backupcfg/urls.py
from django.urls import path
from .views import backup_cfg

app_name = 'backupcfg'


urlpatterns = [
    path('', backup_cfg, name='backup_cfg'),
]

networkmgmt/bulksendcfg/urls.py
from django.urls import path
from .views import bulk_send_cmd

app_name = 'bulksendcfg'


urlpatterns = [
    path('', bulk_send_cmd, name='bulk_send_cmd'),
]

networkmgmt/core/urls.py
from django.urls import path
from . import views

app_name = 'core'


urlpatterns = [
    path('', views.index, name='index'),
    path('save_file/', views.save_file, name='save_file'),
]

networkmgmt/networkmgmt/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('backupcfg/', include('backupcfg.urls', namespace='backupcfg')),
    path('bulkcfg/', include('bulksendcfg.urls', namespace='bulksendcfg')),
    path('swportmgmt/', include('swportmgmt.urls', namespace='swportmgmt')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

networkmgmt/swportmgmt/urls.py
from django.urls import path
from .views import (
    switch_port_mgmt,
    MainView,
    SwitchPortSearchFormView,
    SwitchPortMgmtFormView
)

app_name = 'swportmgmt'


urlpatterns = [
    # path('', switch_port_mgmt, name='switch_port_mgmt'),
    path('', MainView.as_view(), name='switch_port_mgmt'),
    path('search/', SwitchPortSearchFormView.as_view(), name='search'),
    path('switchportmgmt/', SwitchPortMgmtFormView.as_view(), name='switchportmgmt'),
]

networkmgmt/users/urls.py
# Импортируем из приложения django.contrib.auth нужный view-класс
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView, PasswordChangeView,
    PasswordChangeDoneView, PasswordResetDoneView,
    PasswordResetConfirmView, PasswordResetCompleteView
)
from django.urls import path
# from . import views

app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/',
         LoginView.as_view(template_name='users/login.html'),
         name='login'
         ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
]

networkmgmt/templates/includes/footer.html
<!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
<p>© {{ year }} Copyright <span style="color:red">Ne</span>TZeN</p>

networkmgmt/templates/includes/form_base.html
{% extends "base.html" %}
{% block title %} title {% endblock %}
{% block content %}
  <script>
    function openLoader() {
        document.getElementById("loadingModal").style.display = "block";
      }
  </script>
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% block card_header %} card_header {% endblock %}
        </div>
          <div class="card-body">
          {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                        {{ field.id_for_label }} 1 {{ field.value }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                      {{ field.id_for_label }} 2 {{ field.value }}
                    </div>
                  {% endfor %}
              {% endif %}

              {# Передаем форму #}
              {% block form_body %} {% endblock %}
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %}
              <div class="form-group row my-3"
                {% if field.field.required %}
                  aria-required="true"
                {% else %}
                  aria-required="false"
                {% endif %}
              >
              <label for="{{ field.id_for_label }}">
                  {% if field.is_hidden %}
                    {{ field }}
                  {% elif field %}
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  {% endif %}
              </label>
              </div>
              <div>
                {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
              {% endfor %}
              <br>
              <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-primary">
                {% block button_name %}{% endblock %}
                </button>
                {% block ext_data %}{% endblock %}
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
        <div id="loadingModal" style="display: none;">
          <br>
          <div class="d-flex justify-content-between text-primary">
            <strong>Отправка команд...</strong>
            <div class="spinner-border ms-auto text-primary" role="status" aria-hidden="true"></div>
          </div>
          <br>
        </div>
      </div> <!-- col -->
    </div> <!-- row -->
        <div class="col-md-12 d-flex justify-content-center p-3">
        {% if messages %}
          {% block messages %}{% endblock %}
        {% endif %}  
        {% if save_file %}
        </div>
            <div class="d-flex justify-content-center p-2">
              <button class="btn btn-primary" 
                      type="submit" 
                      onclick="location.href='{% url 'core:save_file' %}'" 
                      name='mybtn2'>
                Download file
              </button>
            </div>
        {% endif %}   
{% endblock %}

networkmgmt/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'core:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Net</span>work MGMT
      </a>
      {% comment %}
      Меню - список пунктов со стандартными классами Bootsrap.
      Класс nav-pills нужен для выделения активных пунктов
      {% endcomment %}
      <ul class="nav nav-pills">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link link-light active"
             href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li class="nav-item d-flex justify-content-between align-items-center">
          <h6 class="btn">Пользователь: {{ user.username }}</h6>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
</header>
{% endwith %}

networkmgmt/templates/includes/sidebar.html
{% with request.resolver_match.view_name as view_name %}
<div class="d-flex flex-column flex-shrink-0  bg-light">
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <a href="{% url 'core:index' %}" class="nav-link {% if view_name  == 'core:index' %}active{% endif %}">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
            Главная страница
        </a>
      </li>
      <li class="nav-item">
        <a href="{% url 'backupcfg:backup_cfg' %}"
           class="nav-link {% if view_name  == 'backupcfg:backup_cfg' %}active{% endif %}">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#database-down"></use></svg>
            Резервное копирование конфигураций АСО
        </a>
      </li>
      <li class="nav-item">
        <a href="{% url 'bulksendcfg:bulk_send_cmd' %}"
           class="nav-link {% if view_name  == 'bulksendcfg:bulk_send_cmd' %}active{% endif %}">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg>
            Настройка группы устройств
        </a>
      </li>
      <li>
        <a href="{% url 'swportmgmt:switch_port_mgmt' %}" 
           class="nav-link {% if view_name  == 'swportmgmt:switch_port_mgmt' %}active{% endif %}">
          <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#outlet"></use></svg>
          Управление портами коммутаторов
        </a>
      </li>
      <li>
        <a href="#" class="nav-link link-dark">
          <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#grid"></use></svg>
          Products
        </a>
      </li>
      <li>
        <a href="#" class="nav-link link-dark">
          <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#people-circle"></use></svg>
          Customers
        </a>
      </li>
    </ul>
    <hr>
  </div>
{% endwith %}